# This workflow performs integration tests on the app, builds a package with Maven, and builds a Docker image for the app.

name: Test + Build + Docker

on:
  push:
    branches:
    - main    # if a pull request is closed with merge, that will also trigger a push event
    - ci/*

jobs:
  integration-tests:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: "Fetch the repository's code to the runner machine"
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
      
    - name: Testing
      run: ./mvnw clean integration-test

  
  maven-build:

    needs: integration-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: "Fetch the repository's code to the runner machine"
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: ./mvnw clean package verify

    - name: Upload artifact for the docker-build job
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'

  
  docker-build:

    needs: maven-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: "Fetch the repository's code to the runner machine"
      uses: actions/checkout@v4
    
    - name: Download artifact from the maven-build job
      uses: actions/checkout@v4
      with:
        name: java-app
    
    - name: Log in to GHCR with Docker
      run: docker login ghcr.io -u nyjgit -p ${{ github.token }}

    - name: Build the Docker image
      run: docker build --tag ghcr.io/nyjgit/cubix/1/optional/app:springboot .

    - name: Publish the Docker image to GHCR
      run: docker push ghcr.io/nyjgit/cubix/1/optional/app:springboot
