# This workflow performs unit tests on the app.

name: Unit tests

on:
  push:
    branches:
    - feature/*
    - ci/*

jobs:
  unit-tests:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: "Fetch the repository's code to the runner machine"
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
      
    - name: Testing
      run: ./mvnw clean test